# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend_class', models.CharField(help_text='the backend of load app', max_length=1024)),
                ('update_time', models.DateTimeField(auto_now=True, help_text='the updatetime of update backend')),
            ],
        ),
    ]
