# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-03 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo_Img_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(help_text='image name', max_length=40)),
                ('tag_name', models.CharField(help_text='tag name', max_length=40)),
                ('update_time', models.DateTimeField(auto_now=True, help_text='the time of update photo image tag')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.Photo')),
            ],
        ),
    ]
