# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-06 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_number', models.CharField(help_text='teacher ID', max_length=1024)),
                ('grade_number', models.CharField(help_text='grade ID', max_length=1024)),
                ('content_table', models.TextField(default='', help_text='the tag of show')),
                ('create_time', models.DateTimeField(auto_now=True, help_text='the time of update')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='grade ID', max_length=1024)),
                ('name', models.CharField(help_text='grade name', max_length=1024)),
                ('create_time', models.DateTimeField(auto_now=True, help_text='the time of update')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='teacher ID', max_length=1024)),
                ('name', models.CharField(help_text='teacher name', max_length=1024)),
                ('create_time', models.DateTimeField(auto_now=True, help_text='the time of update')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.Grade')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.Teacher'),
        ),
    ]
