# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True, help_text='the time of wait teacher this month')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.Teacher')),
            ],
        ),
    ]
